server:
  servlet:
    context-path: /
  port: 9001

spring:
  application:
    name: finance-data
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: finance-data
    url: jdbc:postgresql://localhost:5432/hy_platform?useSSL=false&allowMultiQueries=true
    username: postgres
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9000
    executor:
      appname: xxl-job-executor-financial-data-dispatch
      ip: 127.0.0.1
      port: 9101
      logpath: ./applogs
      logretentiondays: -1

mybatis:
  #configuration:
    #logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  #config-location: classpath:mybatis-config.xml
logging:
  file: logs/finance-data.log
